//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleMoneyTransform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleMoneyTransform.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///    xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        ///    xmlns:func=&quot;urn:script-functions&quot; exclude-result-prefixes=&quot;msxsl func&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;!--ENTRY POINT--&gt;
        ///  &lt;xsl:template match=&quot;/div&quot;&gt;
        ///  	  &lt;!--/div[@class=&apos;au-deals-list&apos;]--&gt;
        ///    &lt;MoneyOrders&gt;
        ///		&lt;xsl:for-each select=&quot;div&quot;&gt;
        ///			&lt;MoneyOrder&gt;
        ///
        ///				&lt;Time&gt;
        ///					&lt;xsl:value-of select=&quot;small[@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Finance_i_ua_TransformSchema {
            get {
                return ResourceManager.GetString("Finance_i_ua_TransformSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///    xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        ///    xmlns:func=&quot;urn:script-functions&quot; exclude-result-prefixes=&quot;msxsl func&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///  &lt;!--ENTRY POINT--&gt;
        ///  &lt;xsl:template match=&quot;/div&quot;&gt;
        ///  	  &lt;!--/div[@class=&apos;au-deals-list&apos;]--&gt;
        ///    &lt;MoneyOrders&gt;
        ///		&lt;xsl:for-each select=&quot;div&quot;&gt;
        ///			&lt;MoneyOrder&gt;
        ///
        ///				&lt;Time&gt;
        ///					&lt;xsl:value-of select=&quot;small[@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinfinTransformSchema {
            get {
                return ResourceManager.GetString("MinfinTransformSchema", resourceCulture);
            }
        }
    }
}
